steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cosmic-weave/flontend', '-f', 'Dockerfile-frontend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cosmic-weave/flontend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flontend'
      - '--image'
      - 'gcr.io/cosmic-weave/flontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=8080'

images:
  - 'gcr.io/cosmic-weave/flontend'
